# Generated by Django 4.1.5 on 2023-01-27 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tostadora_product_presentation',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('picture', models.CharField(max_length=1000)),
                ('stock', models.IntegerField()),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.presentation')),
            ],
            options={
                'db_table': 'tostadora_product',
            },
        ),
    ]
