# Generated by Django 4.1.5 on 2023-01-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
