# Generated by Django 4.1.5 on 2023-01-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_presentation_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='presentation',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Presentation',
        ),
    ]
